
export const ADD_CHANNEL = 'ADD_CHANNEL';
export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL';
export const ADDING_MESSAGE = 'ADDING_MESSAGE';
export const ADD_USERS = 'ADD_USERS';
export const ADD_CURRENT_USERS = 'ADD_CURRENT_USERS';
export const ADD_USERS_IN_CHANNEL = 'ADD_USERS_IN_CHANNEL';
export const ADD_MANY_CHANNEL = 'ADD_MANY_CHANNEL';
export const IS_LOGIN = 'IS_LOGIN';
